---

test_name: Make sure server response matches regex

stages:
  - name: simple match
    request:
      url: http://localhost:5000/token
      method: GET
    response:
      status_code: 200
      body:
        $ext:
          function: tavern.testutils.helpers:validate_regex
          extra_kwargs:
            expression: '<a src=\".*\">'

  - name: save groups
    request:
      url: http://localhost:5000/token
      method: GET
    response:
      status_code: 200
      save:
        $ext:
          function: tavern.testutils.helpers:validate_regex
          extra_kwargs:
            expression: '<a src=\"(.*)\?token=(.*)\">'

  - name: send saved
    request:
      url: "{regex.groups[0]}"
      method: GET
      params:
        token: "{regex.groups[1]}"
    response:
      status_code: 200
